### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by avalentino** [insarlab/PySolid#35]
The `setup.py` file has been recently updated to specify the license as `license='GPL-3.0-or-later'`.

Anyway in the classifiers section it is is specified:
 
`License :: OSI Approved :: GNU General Public License v3 (GPLv3)`

which corresponds to `GPL-3.0-only`, while `GPL-3.0-or-later` corresponds to

`License :: OSI Approved :: GNU Lesser General Public License v3 or later (LGPLv3+)`

Please clarify the licensing.

**Comment by yunjunz** [comment]
`license='GPL-3.0-or-later'` is a typo and has been removed in #36. The license is `GPLv3`, as indicated in the license file and classifier. Thank you for catching this.

**Comment by avalentino** [comment]
Dear @yunjunz, thanks a lot for the clarification.
Please note, anyway, that the attached license file is identical for GPL-3only and GPL-3+ (https://spdx.org/licenses/GPL-3.0-only.html).

For this reason I recommend, for the next release, to specify the `license='GPL-3.0-only'` in the `setup.py` in addition to classifiers, and/or to clearly state which is the applicable GPL variant in the `README.md` file.

Finally a question, just for my curiosity, have you considered to use LGPL instead of GPL?

**Comment by yunjunz** [comment]
Thank you for the suggestion @avalentino. I did not realize that `GPLv3` and `GPLv3+` have the same license file. I would be happy to switch to GPLv3+ for more flexible reusability, for both `pysolid` and `mintpy`, I will check with the `pyaps` owner for this as well.

> Finally a question, just for my curiosity, have you considered to use LGPL instead of GPL?

I have considered the LGPL license and still prefer the ordinary GPL ones.

**Comment by avalentino** [comment]
Closed via #37
