### ISSUE TITLE
Support for ARM64-based MacOS via pip or conda

### ISSUE THREAD

**Issue by forrestfwilliams** [insarlab/PySolid#61]
In addition to the `x86_64` builds currently supported by `pysolid`, it would be great if you could support an `arm64` build for MacOS. This would enable newer Mac users to use `pysolid`. Also, since `pysolid` is a dependency of `MintPy`, `MintPy` is not currently installable on `arm64` Macs.

A pip-installable version of `pysolid` would fix my immediate issue, but long-term it would be good to have conda support as well.

I have tried to install `pysolid` via pip, but ran into low-level errors when trying to build the `pysolid` wheels. I'm happy to provide the error messages here if they would be useful.

**Comment by scottstanie** [comment]
error messages would be great!
Also if you know of any small tricks to get the conda forge recipe to build for arm64, that would be great. 
I'm guessing it's something for the [host requirements](https://github.com/conda-forge/pysolid-feedstock/blob/main/recipe/meta.yaml#L24-L35) to get the right fortran compiler for arm Macs. I do know that I can build pysolid on my local laptop which is an M1 mac, so nothing in the actual code needs to change to make this happen

**Comment by scottstanie** [comment]
Closed by https://github.com/conda-forge/pysolid-feedstock/pull/13 

```
$ uname -m
arm64

$ mamba install pysolid
...
  + pysolid    0.3.0  py310hf631ce7_0  conda-forge/osx-arm64     84kB

```

**Comment by yunjunz** [comment]
Great to see that PR is merged and pysolid is now available on Apple Silicon! Thank you @scottstanie!
