### ISSUE TITLE
Support Python 3.12+

### ISSUE THREAD

**Issue by jhkennedy** [insarlab/PySolid#78]
PySolid currently does not support Python 3.12+ because it relies on `numpy.distutils` to build the compiled Fortran extension. `numpy.distutils` has been removed for Python 3.12+ builds of numpy:
https://numpy.org/devdocs/reference/distutils_status_migration.html#distutils-status-migration

Reccomendations there are to upgrade to:
- :x: `setuptools` which we cannot do because it doesn't support Fortran
- :grey_question: [Meson](https://mesonbuild.com/), and the [meson-python](https://meson-python.readthedocs.io/) build backend
- :grey_question: [CMake](https://cmake.org/), and the [scikit-build-core](https://scikit-build-core.readthedocs.io/en/latest/) build backend

I (@jhkennedy) lean towards scikit-build-core out of familiarity, but I haven't used mesons enough to have a well-formed opinion.

**Comment by yunjunz** [comment]
Either `CMake` or `Meson` sounds good to me. I don't have a preference. Tagging @scottstanie for discussion.

**Comment by rtburns-jpl** [comment]
Hey guys, now that pysolid is a requirement of isce3 we want to fix this so we can support python 3.12+, so I'm planning to work on this. Let me know if anyone has a WIP build system migration, otherwise I'll PR my own implementation.

**Comment by jhkennedy** [comment]
@rtburns-jpl Fantastic! I don't think anyone has started on this yet, so a PR of your own implementation would be great. Feel free to tag me for review/help!
